// clients/auth/src/lib/Providers/RedirectionProvider.vue
<template><slot /></template>

<script setup>
import { onMounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';

const router = useRouter();
const route = useRoute();
const currentPathRef = ref(route.fullPath);

onMounted(() => {
  window.addEventListener('parent-redirection', event => {
    if (event.detail.path !== currentPathRef.value) {
      router.push(event.detail.path);
    }
  });
});

watch(route, to => {
  currentPathRef.value = to.fullPath;
  const event = new CustomEvent('child-redirection', {
    bubbles: true,
    cancelable: true,
    detail: { path: to.fullPath },
  });
  window.dispatchEvent(event);
});
</script>

// clients/bank/src/lib/providers/RedirectionProvider.tsx
import { FC, useRef, Fragment, PropsWithChildren, useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';

interface RedirectionObj {
  path: string;
}

const RedirectionProvider: FC<PropsWithChildren> = ({ children }) => {
  const location = useLocation();
  const navigate = useNavigate();
  const currentPathRef = useRef<string>(location.pathname);

  useEffect(() => {
    //@ts-ignore
    window.addEventListener('parent-redirection', (event: CustomEvent<RedirectionObj>) => {
      if (event.detail.path !== currentPathRef.current) {
        navigate(event.detail.path);
      }
    });
  }, []);

  useEffect(() => {
    currentPathRef.current = location.pathname;
    const event = new CustomEvent('child-redirection', {
      bubbles: true,
      cancelable: true,
      detail: { path: location.pathname },
    });
    window.dispatchEvent(event);
  }, [location]);

  return <Fragment>{children}</Fragment>;
};

export default RedirectionProvider;
